### ISSUE TITLE
Soft-signatures on contributions using GitHub

### ISSUE THREAD

**Issue by dcbuild3r** [worldcoin/smtb-ceremony#2]
Please comment your contribution hashes to certify that they match those that you contributed to the ceremony :)

**Comment by dcbuild3r** [comment]
My contribution hashes are:
b10: `b0b44102bf1201e83bffb1cb0c492cfb93421656c4d2d113840bb904a48936c5`
b100: `66e1845efd543078218a92fd575478bd2f71d64b16a3bf427f5032dcc479a808`
b1000: `6a1d0b08bf79fe564cd701e9af70bb5f3936f668869f529e83d8ecb1a3d474b3`

**Comment by kustosz** [comment]
b10: `7f13b7d526ec05775c9646908da8d99a35f48777fa341f8c25adf099135bb162`
b100: `c202ab3e6a3e29041b1e3781cb1ffdbae7683541d32a91d8d92454b2ce0508c2`
b1000: `dc8992e6d8bf5f9ed4b0cf9e98f582c0594d5775f315446c7ed1e94d3020e787`

**Comment by ajvpot** [comment]
@Zellic's contribution hashes are:
b10: `e0e690b8acf0dfd8bed0c65c55c1507fd261ac5eb86ef7f111d04b9a35b81587`
b100: `6ac522c33145afcbcd05291834f13b0b83833578ca1a13e4ef91a33a187f23e2`
b1000: `dca70be8175332c8f3afe78018eecb5c205fef05fc0f177577dfed3bdb562304`

**Comment by vacekj** [comment]
b10: 807552014597a0c51e4e0f2e9b989be7633d8a050906a894cab226bc2a85333d
b100: e2b20b3379496da808a502df477b47846e7c6375a40e84e81730cf5d15142e44
b1000: 606a17d757c56171416c81dcd79171369e6ff651020d0dba0d7c98fa31ce78ca

**Comment by yi-sun** [comment]
b10: `322bd95fe69c2b82e7ecbed4eeed3144869c3ae4a151bb39259d7ead1777d44b`
b100: `491a46c5aca878bd44f2d7d3b940128127eb705cabc6cedb48de74b12a85bf87`
b1000: `7dd5975f1eabee3b51b3e9d2890d558290c55f7cef502cc1fd66fb4e61cc4431`

**Comment by emilianobonassi** [comment]
b10: `d60c8e2b3ceb98c6807f9e541eb163a011cca54ff9d859c5147503e47dcdbc8b`
b100: `8840c48bf70b565fc978cc893f42d8bd597b6904b4d1cd4b48048a39abda6e32`
b1000: `40cecbd461f4cbb275c0a72c182f4481cfcedb5c0b72026ad84b0a007232cbf4`

**Comment by leosayous21** [comment]
b10: `6ae61f6ba229efdd93b7b98e80b5ecf2424038f1fa34e1d941b4ebab15a8d6d8`
b100: `7b13d503f70b5a1c899a5390c51e46d0a2194c1b0d97427ff2f6b074ee2263eb`
b1000: `4c29e019d35c233c1e0f11953293dd42f567ab3d1949afdc4831f8b5c3179c38`

**Comment by r3ld3v** [comment]
b10: `ed4570a3668448102b8f0fa2c47cdd592281a7dd30e568f112ec784b5f1d96e2`
b100: `b136004f834e6a4db35a5def1050d2aed0b4d41df57cbeb4577eb5c5997f9995`
b1000: `d263eafd25ba809748390850966fd689379311033de6d4fc2de69acebb247d2b`

**Comment by stechu** [comment]
b10: `c3092354da6c45b43a81e410364972d635ee563d46c24db77e1dc171f440a9ca`
b100: `30fac7bc6ff5f2bc24991dd5e6537e203714459c1e6d31c241d512490e966dde`
b1000: `9155ac2cc06510ffb63ac9a8c01284bf533183542054a94d735d358cc42cdca4 `

**Comment by kobigurk** [comment]
b10: `d4e581570bbe53ffa9e08cc93816f48486cfd756df50894de74ac1845ae07feb`
b100: `e53e7eae98d270b44e25ac8b413e1dcf45a13062c51cb45e6faad089a25d8511`
b1000: `463c17a0c8ed79c56f4579d1eef02beac8edc91549fc9abae51c08e76b8bb4e9`

**Comment by emlazzarin** [comment]
b10: `43c7cb5dd53447967cfe531ac2120948efd90fa5c80eb3b80fb340df452d7e18`
b100: `3a4112517f6b9082c6d8faf1091164bcd4f818aeb7e53cb8ec2f5aa1eabdd05d`
b1000: `34e92e61360b5e36d44736a8b2b6687c7557985e0acccd770b63de1b710c4506`

**Comment by recmo** [comment]
b10 `1a0925e14d4c3035d8ee5d288e376e723299b712181b4e34b59a337ebe08761a`
b100 `be313375479fa2ce7097129bb187f16df3211dba4e395acdd84e946fb4ae1e4b`
b1000 `1b5bb5f54d1126398b723ae4f42f86d9659550d57af262e67b9f8a6ddc7d926e`

**Comment by m1guelpf** [comment]
b10: `e4ce787995a6c97b8be12f418ae3c026e26f84ad3d433e3fe6f33d3449d08c91`
b100: `10b5376bfbe4e6235a8b7f9b000699063ee8c5c9626e98dc70ed594f5c2e0326`
b1000: `1c512817cc55404489dc0184d7d049e6906f8282c542c17d9817a2bdab8ab524`

**Comment by Dzejkop** [comment]
b10: `2b85850b40ce8659c932e3e829dc21baf79ea8e2c207f40a3bb0257f3e5cb7de`
b100: `f77f2e1cf197b09084c5b16ae0d2a61306ccf4cc01cfa9bab90d2b72ef071a24`
b1000: `ba4fc054df53635a5efc9aac72e9de45a910adebd7da4f67aecd76e22e6ae9cc`
